export const titles = [
  "Url",
  "Public Id",
  "Contrast",
  "Missing Alt Text",
  "Empty Link",
  "Missing Form Label",
  "Linked Image Missing Alt Text",
  "Empty Button",
  "Broken ARIA Reference",
  "Langauge Missing or Invalid",
  "Empty Form Label",
  "Broken ARIA Menu",
  "Empty Heading",
  "Multiple Form Labels",
  "Spacer Image Missing Alt Text",
  "Empty Table Header",
  "Broken Skip Link",
  "Missing or Uninformative Page Title",
  "Image Map Missing Alt Text",
  "Image Button Missing Alt Text",
  "Image Map Area Missing Alt Text",
  "Page Refreshes or Redirects",
  "Blinking Content",
  "Invalid Longdesc",
  "Marquee",
];

export const fields = [
  "url",
  "publicId",
  "very_low_contrast",
  "missing_alternative_text",
  "empty_link",
  "missing_form_label",
  "linked_image_missing_alternative_text",
  "empty_button",
  "broken_aria_reference",
  "language_missing_or_invalid",
  "empty_form_label",
  "broken_aria_menu",
  "empty_heading",
  "multiple_form_labels",
  "spacer_image_missing_alternative_text",
  "empty_table_header",
  "broken_skip_link",
  "missing_or_uninformative_page_title",
  "image_map_missing_alternative_text",
  "image_button_missing_alternative_text",
  "image_map_area_missing_alternative_text",
  "page_refreshes_or_redirects",
  "blinking_content",
  "invalid_longdesc",
  "marquee",
];
